DROP DATABASE IF EXISTS `burgers_db`;
CREATE DATABASE `burgers_db`;

DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers 
(

id int NOT NULL AUTO_INCREMENT,
burger_name VARCHAR (255) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)

)
